package projectupgrade

import (
	"fmt"
	"strings"
)

// ReleaseNotesURL returns the GitHub release notes page for a Shopware
// version, so version pickers and reports can link to the changelog.
func ReleaseNotesURL(shopwareVersion string) string {
	return "https://github.com/shopware/shopware/releases/tag/v" + strings.TrimPrefix(shopwareVersion, "v")
}

// systemRequirementsURL documents Shopware's per-version system requirements
// (PHP, database, Redis, …).
const systemRequirementsURL = "https://developer.shopware.com/docs/guides/installation/requirements.html"

// ReportData collects everything that goes into the exportable upgrade
// support report.
type ReportData struct {
	CurrentVersion string
	TargetVersion  string
	// Environment is the executor type the upgrade runs in (local, docker, …).
	Environment string
	// PHPConstraint is the PHP requirement of the target version ("" when it
	// could not be determined).
	PHPConstraint string
	Preflight     []PreflightResult
	Extensions    []ExtensionRow
	// ComposerJSON is the raw contents of the project composer.json.
	ComposerJSON string
	// ComposerOutput is the raw output of the composer compatibility check.
	// It is attached to the report when dependency blockers were detected.
	ComposerOutput []string
}

// BuildMarkdownReport renders a support-ready Markdown report of the upgrade
// plan: context, system requirement changes, extension findings grouped into
// OK / needed review / was blocked, the project composer.json, and — when
// blockers exist — the raw composer output.
func BuildMarkdownReport(d ReportData) string {
	var b strings.Builder

	b.WriteString("# Shopware Upgrade Report\n\n")
	b.WriteString("Generated by `shopware-cli project upgrade`. Attach this report to support or extension vendor tickets.\n\n")

	b.WriteString("## Upgrade context\n\n")
	fmt.Fprintf(&b, "- Current Shopware version: `%s`\n", d.CurrentVersion)
	fmt.Fprintf(&b, "- Target Shopware version: `%s` ([release notes](%s))\n", d.TargetVersion, ReleaseNotesURL(d.TargetVersion))
	if d.Environment != "" {
		fmt.Fprintf(&b, "- Environment: `%s`\n", d.Environment)
	}
	b.WriteString("\n")

	b.WriteString("## System requirements\n\n")
	if d.PHPConstraint != "" {
		fmt.Fprintf(&b, "- PHP requirement of Shopware %s: `%s`\n", d.TargetVersion, d.PHPConstraint)
	} else {
		fmt.Fprintf(&b, "- PHP requirement of Shopware %s could not be determined.\n", d.TargetVersion)
	}
	fmt.Fprintf(&b, "- Verify database, Redis, and other platform requirements against the official list: %s\n\n", systemRequirementsURL)

	if len(d.Preflight) > 0 {
		b.WriteString("## Preflight checks\n\n")
		for _, r := range d.Preflight {
			marker := "x"
			suffix := ""
			switch r.Status {
			case PreflightFailed:
				marker = " "
				suffix = " — FAILED"
				if r.Explanation != "" {
					suffix += ": " + r.Explanation
				}
			case PreflightSkipped:
				suffix = " — skipped"
				if r.Detail != "" {
					suffix = " — " + r.Detail
				}
			case PreflightOK:
				if r.Detail != "" {
					suffix = " — " + r.Detail
				}
			}
			fmt.Fprintf(&b, "- [%s] %s%s\n", marker, r.Label, suffix)
		}
		b.WriteString("\n")
	}

	writeExtensionBlock(&b, "OK", "These extensions are compatible with the target version.", d.Extensions, ExtensionOK)
	writeExtensionBlock(&b, "Needed review", "These extensions need attention: they will be updated, are deprecated, or were manually marked for removal.", d.Extensions, ExtensionUpdate, ExtensionDeprecated, ExtensionRemove)
	writeExtensionBlock(&b, "Was blocked", "No release compatible with the target version was found. Contact the extension vendor or remove the extension before upgrading.", d.Extensions, ExtensionBlocked)

	if d.ComposerJSON != "" {
		b.WriteString("## composer.json\n\n")
		b.WriteString("```json\n")
		b.WriteString(strings.TrimRight(d.ComposerJSON, "\n"))
		b.WriteString("\n```\n\n")
	}

	if CountBlockers(d.Extensions) > 0 && len(d.ComposerOutput) > 0 {
		b.WriteString("## Raw composer output\n\n")
		b.WriteString("```\n")
		b.WriteString(strings.Join(d.ComposerOutput, "\n"))
		b.WriteString("\n```\n")
	}

	return b.String()
}

func writeExtensionBlock(b *strings.Builder, title, description string, rows []ExtensionRow, states ...ExtensionState) {
	matching := make([]ExtensionRow, 0, len(rows))
	for _, row := range rows {
		for _, state := range states {
			if row.State == state {
				matching = append(matching, row)
				break
			}
		}
	}

	fmt.Fprintf(b, "## Extensions: %s\n\n", title)
	if len(matching) == 0 {
		b.WriteString("None.\n\n")
		return
	}

	b.WriteString(description + "\n\n")
	b.WriteString("| Extension | Installed | Target | Result |\n")
	b.WriteString("| --- | --- | --- | --- |\n")
	for _, row := range matching {
		target := row.Target
		if target == "" {
			target = "—"
		}
		fmt.Fprintf(b, "| `%s` | %s | %s | %s |\n", row.Name, row.Current, target, row.Result)
	}
	b.WriteString("\n")
}
