package storage

import (
	"fmt"
	"strings"
)

// Default environment variable names used to keep the S3 credentials out of the
// committed YAML config.
const (
	DefaultAccessKeyEnv = "STORAGE_S3_ACCESS_KEY"
	DefaultSecretKeyEnv = "STORAGE_S3_SECRET_KEY"
)

// ConfigOptions bundles everything needed to render the Shopware filesystem
// configuration for a set of migrated datastores.
type ConfigOptions struct {
	Connection   S3Connection
	Targets      []StoreTarget
	AccessKeyEnv string
	SecretKeyEnv string
	// PublicACL adds options.visibility "public" for public datastores.
	PublicACL bool
}

func (o ConfigOptions) accessKeyEnv() string {
	if o.AccessKeyEnv != "" {
		return o.AccessKeyEnv
	}
	return DefaultAccessKeyEnv
}

func (o ConfigOptions) secretKeyEnv() string {
	if o.SecretKeyEnv != "" {
		return o.SecretKeyEnv
	}
	return DefaultSecretKeyEnv
}

// EnvVars returns the environment variables (name -> value) that should be
// written to .env.local so the generated config can resolve the credentials.
func (o ConfigOptions) EnvVars() map[string]string {
	return map[string]string{
		o.accessKeyEnv(): o.Connection.AccessKey,
		o.secretKeyEnv(): o.Connection.SecretKey,
	}
}

// RenderFilesystemConfig renders a Shopware config/packages YAML file that
// points the given datastores at the configured S3 storage. Credentials are
// referenced via %env(...)% placeholders.
func RenderFilesystemConfig(o ConfigOptions) string {
	var b strings.Builder

	b.WriteString("# Generated by shopware-cli (project storage migrate).\n")
	b.WriteString("# The S3 credentials are read from environment variables; set them in\n")
	b.WriteString("# .env.local (local) or your deployment secrets (production).\n")
	b.WriteString("shopware:\n")
	b.WriteString("    filesystem:\n")

	for _, t := range o.Targets {
		writeStore(&b, o, t)
	}

	return b.String()
}

func writeStore(b *strings.Builder, o ConfigOptions, t StoreTarget) {
	ind := "        " // 8 spaces (2 levels below shopware:)

	fmt.Fprintf(b, "%s%s:\n", ind, t.Datastore.Name)
	fmt.Fprintf(b, "%s    type: \"amazon-s3\"\n", ind)
	if t.PublicURL != "" {
		fmt.Fprintf(b, "%s    url: %q\n", ind, t.PublicURL)
	}
	fmt.Fprintf(b, "%s    config:\n", ind)
	fmt.Fprintf(b, "%s        bucket: %q\n", ind, t.Bucket)

	region := o.Connection.Region
	if region == "" {
		region = "us-east-1"
	}
	fmt.Fprintf(b, "%s        region: %q\n", ind, region)

	if o.Connection.Endpoint != "" {
		fmt.Fprintf(b, "%s        endpoint: %q\n", ind, o.Connection.Endpoint)
	}
	if o.Connection.UsePathStyle {
		fmt.Fprintf(b, "%s        use_path_style_endpoint: true\n", ind)
	}
	if root := strings.Trim(t.Root, "/"); root != "" {
		fmt.Fprintf(b, "%s        root: %q\n", ind, root)
	}
	if o.PublicACL && t.Datastore.Public {
		fmt.Fprintf(b, "%s        options:\n", ind)
		fmt.Fprintf(b, "%s            visibility: \"public\"\n", ind)
	}
	fmt.Fprintf(b, "%s        credentials:\n", ind)
	fmt.Fprintf(b, "%s            key: \"%%env(%s)%%\"\n", ind, o.accessKeyEnv())
	fmt.Fprintf(b, "%s            secret: \"%%env(%s)%%\"\n", ind, o.secretKeyEnv())
}
