package proxy

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// overrideMarker identifies override files generated by shopware-cli, so we
// never touch files the user created themselves.
const overrideMarker = "# Managed by shopware-cli project proxy."

// composeBaseFiles are the compose file names docker compose discovers, in
// lookup order, mapped to the override file name belonging to them.
var composeBaseFiles = []struct {
	base     string
	override string
}{
	{"compose.yaml", "compose.override.yaml"},
	{"compose.yml", "compose.override.yml"},
	{"docker-compose.yml", "docker-compose.override.yml"},
	{"docker-compose.yaml", "docker-compose.override.yaml"},
}

const composeOverrideTemplate = overrideMarker + ` Remove it with "shopware-cli project proxy remove".
services:
  %[4]s:
    networks:
      - default
      - %[1]s
    environment:
      TRUSTED_PROXIES: "127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
      SYMFONY_TRUSTED_PROXIES: "127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
    labels:
      traefik.enable: "true"
      traefik.docker.network: "%[1]s"
      traefik.http.routers.%[2]s.rule: "Host(` + "`%[3]s`" + `)"
      traefik.http.routers.%[2]s.entrypoints: "websecure"
      traefik.http.routers.%[2]s.tls: "true"
      traefik.http.services.%[2]s.loadbalancer.server.port: "%[5]d"
      ` + HostLabel + `: "%[3]s"

networks:
  %[1]s:
    external: true
`

// ComposeOverride renders the docker compose override file attaching a
// project's web service to the shared proxy network.
func ComposeOverride(name, host, service string, upstreamPort int) string {
	return fmt.Sprintf(composeOverrideTemplate, NetworkName, name, host, service, upstreamPort)
}

// OverridePath determines the override file path for the compose project in
// projectRoot. It returns an error when no compose file exists.
func OverridePath(projectRoot string) (string, error) {
	for _, files := range composeBaseFiles {
		if fileExists(filepath.Join(projectRoot, files.base)) {
			return filepath.Join(projectRoot, files.override), nil
		}
	}

	return "", fmt.Errorf("no docker compose file found in %s, the proxy currently supports docker compose based setups only", projectRoot)
}

// WriteComposeOverride writes the override file for the project. It refuses
// to overwrite an override file that was not generated by shopware-cli.
func WriteComposeOverride(projectRoot, name, host, service string, upstreamPort int) (string, error) {
	path, err := OverridePath(projectRoot)
	if err != nil {
		return "", err
	}

	if content, err := os.ReadFile(path); err == nil && !strings.HasPrefix(string(content), overrideMarker) {
		return "", fmt.Errorf("%s already exists and was not created by shopware-cli, please add the proxy configuration manually", path)
	}

	if err := os.WriteFile(path, []byte(ComposeOverride(name, host, service, upstreamPort)), 0o644); err != nil {
		return "", err
	}

	return path, nil
}

// RemoveComposeOverride deletes a previously generated override file. It
// refuses to delete files not generated by shopware-cli.
func RemoveComposeOverride(projectRoot string) (string, error) {
	path, err := OverridePath(projectRoot)
	if err != nil {
		return "", err
	}

	content, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return "", fmt.Errorf("no proxy configuration found in %s", projectRoot)
		}

		return "", err
	}

	if !strings.HasPrefix(string(content), overrideMarker) {
		return "", fmt.Errorf("%s was not created by shopware-cli, refusing to delete it", path)
	}

	if err := os.Remove(path); err != nil {
		return "", err
	}

	return path, nil
}
