package docker

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/shyim/go-composer"
	"gopkg.in/yaml.v3"

	"github.com/shopware/shopware-cli/internal/symfony"
)

// overrideMarker is the first line of every override file generated by
// `project proxy`, so user-created override files are never touched.
const overrideMarker = "# Managed by shopware-cli project proxy. Do not edit manually."

// overrideFileName is docker compose's standard override file, merged with
// compose.yaml automatically by every `docker compose` invocation.
const overrideFileName = "compose.override.yaml"

// ProxyOptions carries the data needed to route a project's services through
// the shared shopware-cli proxy by hostname instead of fixed host ports.
type ProxyOptions struct {
	// Hostname is the project's resolved root hostname, e.g.
	// "my-shop.shopware.local". Every other route is a subdomain of it (e.g.
	// "admin-watch.my-shop.shopware.local").
	Hostname string
	// NetworkName is the external Docker network shared with Traefik.
	NetworkName string
	// CAPath is the host path of the proxy's root CA certificate. When set,
	// it is mounted read-only into the shop's containers so code running
	// there (Node via NODE_EXTRA_CA_CERTS, and PHP once the image trusts the
	// anchor) accepts the proxy's HTTPS certificates — needed when the shop
	// calls its own APP_URL over HTTPS (and, as a side effect, a sibling's).
	CAPath string
	// AppURL, when set, pins APP_URL as a real container env var on the web and
	// background services. It must be set here (not only in .env.local) because
	// the container is created before proxy up rewrites .env.local, and a real
	// env var reliably beats both the env_file and the image default — otherwise
	// PHP renders absolute asset URLs (e.g. the storefront import map) with the
	// stale image APP_URL.
	AppURL string
}

// containerCAPath is where the proxy CA is mounted inside the shop's
// containers. /usr/local/share/ca-certificates is the standard anchor
// directory picked up by update-ca-certificates, and the file is also
// referenced directly by NODE_EXTRA_CA_CERTS.
const containerCAPath = "/usr/local/share/ca-certificates/shopware-cli-proxy.crt"

// proxyRoute describes one HTTP endpoint of a service that gets routed
// through the shared proxy: its subdomain (empty means the project's root
// hostname) and the container port it is served on.
type proxyRoute struct {
	subdomain     string
	containerPort int
}

// hostname returns the full hostname for this route, e.g.
// "admin-watch.my-shop.shopware.local" or, for the root route,
// "my-shop.shopware.local".
func (p *ProxyOptions) hostname(r proxyRoute) string {
	if r.subdomain == "" {
		return p.Hostname
	}

	return fmt.Sprintf("%s.%s", r.subdomain, p.Hostname)
}

// GenerateComposeOverride renders the compose override that switches the
// project into proxy mode: it resets the fixed host ports of every routed
// service (requires docker compose >= 2.24 for the !reset tag), joins them to
// the shared proxy network and adds the Traefik routing labels. The
// backgroundServices (worker, scheduler) get no routes but still join the
// shared network and carry the CA, so their PHP console processes can call
// the shop's own APP_URL over TLS. The base compose.yaml stays untouched, so
// deleting the override restores fixed-port mode.
func GenerateComposeOverride(lock *composer.Lock, opts *ProxyOptions, backgroundServices []string) ([]byte, error) {
	services := newMappingNode()

	web := overrideService(opts, "web",
		proxyRoute{subdomain: "", containerPort: 8000},
		proxyRoute{subdomain: "admin-watch", containerPort: 5173},
		proxyRoute{subdomain: "storefront-watch", containerPort: 9998},
	)
	// Traefik terminates TLS and forwards plain HTTP from a private container
	// address; Shopware must trust its X-Forwarded-* headers or URL
	// generation and redirects fall back to http.
	webEnv := newMappingNode()
	addKeyValue(webEnv, "TRUSTED_PROXIES", "127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16")
	addKeyValue(webEnv, "SYMFONY_TRUSTED_PROXIES", "127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16")
	if opts.AppURL != "" {
		addKeyValue(webEnv, "APP_URL", opts.AppURL)
	}
	mountCA(web, webEnv, opts.CAPath)
	addKeyValueNode(web, "environment", webEnv)
	addKeyValueNode(services, "web", web)

	addKeyValueNode(services, "adminer", overrideService(opts, "adminer", proxyRoute{subdomain: "adminer", containerPort: 8080}))
	addKeyValueNode(services, "mailer", overrideService(opts, "mailer", proxyRoute{subdomain: "mailer", containerPort: 8025}))

	if lock.GetPackage("symfony/amqp-messenger") != nil {
		addKeyValueNode(services, "lavinmq", overrideService(opts, "lavinmq", proxyRoute{subdomain: "lavinmq", containerPort: 15672}))
	}

	if lock.GetPackage("shopware/elasticsearch") != nil {
		addKeyValueNode(services, "opensearch", overrideService(opts, "opensearch", proxyRoute{subdomain: "opensearch", containerPort: 9200}))
	}

	for _, name := range backgroundServices {
		addKeyValueNode(services, name, attachedService(opts))
	}

	externalNetwork := newMappingNode()
	addKeyValueNode(externalNetwork, "external", newBoolNode(true))

	networks := newMappingNode()
	addKeyValueNode(networks, opts.NetworkName, externalNetwork)

	root := newMappingNode()
	addKeyValueNode(root, "services", services)
	addKeyValueNode(root, "networks", networks)

	doc := yaml.Node{Kind: yaml.DocumentNode, Content: []*yaml.Node{root}}

	out, err := yaml.Marshal(&doc)
	if err != nil {
		return nil, err
	}

	header := overrideMarker + "\n" +
		"# It routes this project through the shared proxy; \"shopware-cli project proxy down\" removes it.\n\n"

	return append([]byte(header), out...), nil
}

// overrideService builds one service's override: fixed host ports are
// cleared, the service joins the shared proxy network and gets a Traefik
// router per route.
func overrideService(opts *ProxyOptions, serviceName string, routes ...proxyRoute) *yaml.Node {
	svc := newMappingNode()

	// !reset clears the ports list of the base file instead of merging into
	// it (docker compose >= 2.24).
	addKeyValueNode(svc, "ports", &yaml.Node{Kind: yaml.SequenceNode, Tag: "!reset", Style: yaml.FlowStyle})
	addKeyValueNode(svc, "networks", newSequenceNode("default", opts.NetworkName))

	labels := newMappingNode()
	addKeyValue(labels, "traefik.enable", "true")
	addKeyValue(labels, "traefik.docker.network", opts.NetworkName)

	// Router/service names must be unique across every project sharing the
	// one Traefik instance, so they are prefixed with the project's own
	// hostname (dots replaced, since Traefik router names must be alphanumeric).
	routerPrefix := strings.ReplaceAll(opts.Hostname, ".", "-") + "-" + serviceName

	for _, route := range routes {
		router := routerPrefix
		if route.subdomain != "" && route.subdomain != serviceName {
			router = router + "-" + route.subdomain
		}

		addKeyValue(labels, fmt.Sprintf("traefik.http.routers.%s.rule", router), fmt.Sprintf("Host(`%s`)", opts.hostname(route)))
		addKeyValue(labels, fmt.Sprintf("traefik.http.routers.%s.entrypoints", router), "websecure")
		addKeyValue(labels, fmt.Sprintf("traefik.http.routers.%s.tls", router), "true")
		addKeyValue(labels, fmt.Sprintf("traefik.http.routers.%s.service", router), router)
		addKeyValue(labels, fmt.Sprintf("traefik.http.services.%s.loadbalancer.server.port", router), fmt.Sprintf("%d", route.containerPort))
	}

	addKeyValueNode(svc, "labels", labels)

	return svc
}

// attachedService joins a background console service (worker, scheduler) to
// the shared proxy network and mounts the CA, without exposing any HTTP
// route — so its PHP process can reach the shop's own APP_URL over TLS, but
// nothing is published for it.
func attachedService(opts *ProxyOptions) *yaml.Node {
	svc := newMappingNode()
	addKeyValueNode(svc, "networks", newSequenceNode("default", opts.NetworkName))

	env := newMappingNode()
	if opts.AppURL != "" {
		addKeyValue(env, "APP_URL", opts.AppURL)
	}
	mountCA(svc, env, opts.CAPath)
	if len(env.Content) > 0 {
		addKeyValueNode(svc, "environment", env)
	}

	return svc
}

// mountCA mounts the proxy CA read-only into svc and points
// NODE_EXTRA_CA_CERTS at it in env, so code in the container trusts the
// proxy's HTTPS certificates. Node reads the PEM directly; PHP/curl needs the
// image to run update-ca-certificates on the mounted anchor. No-op without a
// CA path. The mount is appended to the base file's volume list (compose
// concatenates sequences), so the project bind mount is preserved.
func mountCA(svc, env *yaml.Node, caPath string) {
	if caPath == "" {
		return
	}

	addKeyValue(env, "NODE_EXTRA_CA_CERTS", containerCAPath)
	addKeyValueNode(svc, "volumes", newSequenceNode(caPath+":"+containerCAPath+":ro"))
}

// WriteComposeOverride writes the proxy override file for the project. It
// refuses to overwrite an override file the user created themselves.
func WriteComposeOverride(projectFolder string, opts *ProxyOptions) error {
	path := filepath.Join(projectFolder, overrideFileName)

	if content, err := os.ReadFile(path); err == nil && !strings.HasPrefix(string(content), overrideMarker) {
		return fmt.Errorf("%s already exists and was not created by shopware-cli: move your customizations to another file (e.g. compose.custom.yaml, loaded via the COMPOSE_FILE variable) and remove it to use the proxy", path)
	}

	lock, err := composer.ReadLock(filepath.Join(projectFolder, "composer.lock"))
	if err != nil {
		return fmt.Errorf("failed to read composer.lock: %w", err)
	}

	background, err := proxyBackgroundServiceNames(projectFolder)
	if err != nil {
		return err
	}

	content, err := GenerateComposeOverride(lock, opts, background)
	if err != nil {
		return err
	}

	return os.WriteFile(path, content, 0o644)
}

// proxyBackgroundServiceNames returns the dedicated console services the base
// compose file contains (the message-queue worker and scheduled-task runner),
// which exist only when the admin worker is disabled — mirroring the check
// WriteComposeFile uses to add them.
func proxyBackgroundServiceNames(projectFolder string) ([]string, error) {
	adminWorkerEnabled, err := symfony.IsAdminWorkerEnabledForProject(projectFolder, "dev")
	if err != nil {
		return nil, fmt.Errorf("failed to read admin worker config: %w", err)
	}

	if adminWorkerEnabled {
		return nil, nil
	}

	names := make([]string, 0, len(BackgroundServices))
	for _, bg := range BackgroundServices {
		names = append(names, bg.Name)
	}

	return names, nil
}

// RemoveComposeOverride deletes the proxy override file. A missing file is
// fine; a user-created override file is left alone.
func RemoveComposeOverride(projectFolder string) error {
	path := filepath.Join(projectFolder, overrideFileName)

	content, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return err
	}

	if !strings.HasPrefix(string(content), overrideMarker) {
		return fmt.Errorf("%s was not created by shopware-cli, refusing to delete it", path)
	}

	return os.Remove(path)
}
