name: Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Project Validate
        uses: shopware/github-actions/project-validate@main
        with:
          phpVersion: '8.4'
