name: Update Base Docker Image
on:
  workflow_dispatch:
  push:
    tags-ignore:
      - "*"
    branches:
      - main
    paths:
      - 'Dockerfile.base'
      - 'internal/verifier/js/**'
      - 'internal/verifier/php/**'
  pull_request:
    paths:
      - 'Dockerfile.base'
      - 'internal/verifier/js/**'
      - 'internal/verifier/php/**'
permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  build:
    name: Build PHP ${{ matrix.php-version }}
    strategy:
      matrix:
        php-version: ["8.5", "8.4", "8.3", "8.2"]
    uses: docker/github-builder/.github/workflows/build.yml@7d2a02426d4b989616ba5aaee4e879afd4134b0d # ratchet:docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read
      id-token: write
      packages: write
    with:
      output: image
      push: ${{ github.event_name != 'pull_request' }}
      platforms: linux/amd64,linux/arm64
      file: Dockerfile.base
      build-args: |
        PHP_VERSION=${{ matrix.php-version }}
      meta-images: |
        ghcr.io/shopware/shopware-cli-base
      meta-tags: |
        type=raw,value=${{ matrix.php-version }}
      meta-flavor: |
        latest=false
      cache: true
      cache-mode: max
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
