name: Tests

on:
  push:
    branches: ["main"]
    tags-ignore:
      - "*"
  pull_request:
    branches: ["main"]

permissions:
  contents: read

env:
  GOTOOLCHAIN: local

jobs:
  build:
    env:
      SHOPWARE_CLI_DISABLE_WASM_CACHE: 1

    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # ratchet:step-security/harden-runner@v2.19.1
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            proxy.golang.org:443
            release-assets.githubusercontent.com:443
            storage.googleapis.com:443

      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # ratchet:actions/setup-go@v6
        with:
          go-version: '1.25'
          check-latest: true
          cache: true

      - name: Download modules
        run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
